services:
  php-fpm:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - redis
    networks:
      - lms-network

  nginx:
    image: nginx:latest
    ports:
      - "8080:80"
    networks:
      - lms-network
    depends_on:
      - php-fpm

  redis:
    volumes:
      - redis-data:/data
    image: redis:alpine
    ports:
      - "6379:6379"
    networks:
      - lms-network

volumes:
  redis-data:
    driver: local
  moodledata:
    driver: local

networks:
  lms-network:
    driver: bridge
