server {
    listen 80;
    server_name localhost;

    root /var/www/html/public;
    index index.php index.html;

    # Limit request body size
    client_max_body_size 5399851000;

    # Set timeout
    proxy_read_timeout 300;
    proxy_connect_timeout 300;
    proxy_send_timeout 300;

    # Set environment variables
    fastcgi_param AWS_ACCESS_KEY_ID minioadmin;
    fastcgi_param AWS_SECRET_ACCESS_KEY minioadmin;

    # Logging
    access_log /var/log/nginx/access.log combined;

    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    location ~ \.php$ {
        include fastcgi_params;
        fastcgi_pass php-fpm:9000;
        fastcgi_index index.php;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
    }

    location ~ /\.ht {
        deny all;
    }
}